
development:
  operation_mode: Test
  is_project_contractor: false
  ignore_payment: [Credit, WebATM, ATM, CVS, Tenpay, TopUpUsed]
  merchant_id: 2000933
  hash_key: XBERn1YOvpM9nfZc
  hash_iv: h1ONHk4P4yqbl5LK

test:
  operation_mode: Test
  is_project_contractor: false
  ignore_payment: [Credit, WebATM, ATM, CVS, Tenpay, TopUpUsed]
  merchant_id: 2000933
  hash_key: XBERn1YOvpM9nfZc
  hash_iv: h1ONHk4P4yqbl5LK

production:
  operation_mode: Test
  is_project_contractor: false
  ignore_payment: [Credit, WebATM, ATM, CVS, Tenpay, TopUpUsed]
  merchant_id: 2000933
  hash_key: XBERn1YOvpM9nfZc
  hash_iv: h1ONHk4P4yqbl5LK